languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "pyyy.xyz"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  description = "pyyy 的个人网站"

[params.author]
  name = "pyyy"
  headline = """👨🏻‍🎓@<a href="https://www.cqu.edu.cn" target="_blank" rel="noopener">重庆大学</a><br>👨🏻‍🔧@<a href="https://mp.weixin.qq.com/s/B3HUb56MBZ4KYMGRqH00rQ" target="_blank" rel="noopener">FRC8214</a><br><a>机械设计制造及其自动化</a><br>📷🚴🤖✈️"""

  image = "img/me.png"
  links = [
    { github = "https://github.com/peterpyyyyy" },
    { bilibili = "https://space.bilibili.com/357505609?spm_id_from=333.1007.0.0"},
    { strava = "https://www.strava.com/athletes/178275168" },
    { email = "mailto:superpyyy@qq.com" },
  ]
